import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

import ProviderTanstackQuery from "@/lib/providers/providers-react-query";
// import ProvidersNextAuth from "@/lib/providers/providers-next-auth";
import ProvidersToaster from "@/lib/providers/providers-toaster";

import { cn } from "@/lib/utils";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                {/* <ProvidersNextAuth> */}
                <ProviderTanstackQuery>
                    <ProvidersToaster>
                        <section
                            className={cn(
                                "w-full h-auto shadow-md"
                                // "bg-gray-800"
                            )}
                        >
                            {children}
                        </section>
                    </ProvidersToaster>
                </ProviderTanstackQuery>
                {/* </ProvidersNextAuth> */}
            </body>
        </html>
    );
}
