import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

import ProviderTanstackQuery from "@/lib/providers/providers-react-query";
// import ProvidersNextAuth from "@/lib/providers/providers-next-auth";
import ProvidersToaster from "@/lib/providers/providers-toaster";

import Navbar from "@/components/headers/navbar";
import Footer from "@/components/headers/footer";

import { cn } from "@/lib/utils";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                {/* <ProvidersNextAuth> */}
                <ProviderTanstackQuery>
                    <ProvidersToaster>
                        <section
                            className={cn(
                                "w-full min-h-screen max-w-5xl mx-auto lg:px-4 lg:py-4",
                            )}
                        >
                            <div className="w-full">
                                <Navbar />
                            </div>
                            <section className="w-full">
                                {children}
                            </section>
                            <div className="w-full">
                                <Footer />
                            </div>
                        </section>
                    </ProvidersToaster>
                </ProviderTanstackQuery>
                {/* </ProvidersNextAuth> */}
            </body>
        </html>
    );
}
